name: Calculate Bounty Based on Events
on:
  push:
  issues:
    types:
      - labeled
      - unlabeled
      - assigned
      - opened
      - closed
  issue_comment:
    types:
      - created
      - edited

jobs:
  calculate_bounty_job:
    # ignore events invoked by bots
    if: >-
      github.event.pull_request.payload.sender.type != 'Bot' && github.repository != 'ubiquity/ubiquibot'
    runs-on: ubuntu-latest
    name: Calculate Bounty with UbiquiBot
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"

      - name: Install
        run: yarn install

      - name: Authenticate as UbiquiBot
        uses: tibdex/github-app-token@v1.7.0
        id: get_installation_token
        with:
          app_id: 396874
          # https://github.com/organizations/ubiquibot/settings/apps/ubiquibot-qa/installations
          # https://github.com/apps/ubiquibot-qa/installations/new/permissions?target_id=4975670
          # https://github.com/settings/installations/38790399
          private_key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpAIBAAKCAQEApveMwJA+HDN3p2gowgspf6ODyCYHgC+QWwMbDIINmrGQ7Go5
            quay/RRz+tFv2mA65Nu9km3/wHKKkBIEU/txs+/7P04pB6RNtGBMesulPWymQw7Y
            KIAeDhEfsernCf1U8O5uVLdn/FzeZOurTqSoIqKMbj1ydBP3Rp+su07iqcfTb4tn
            w/wts+ZwTUtM9+TNrAI3ewmAMPpbdvYzYYHet7O8NFMSoNwkxI0e531lH20oobM2
            jCzCyljvfxW3CxK+e5YoxG//J8VmWUTw3WA0TPEfE+vzgrfYHeAhFE5spy4yLjvt
            G1LN0R3MyvKdMdsXYleT1ZlhJPddP2NSHoTO7QIDAQABAoIBAAJ0EsJlnDQH4ZM5
            KZgoV9TDT1VqkaOlj0Z3Fjep1Y9XWpzOtsg3GZw0Z7vgxfb8gQEJ5ZA4Q5DNXhHd
            4ehmAna1aQi2Gk49cNLcs2L+iRAM/6humGiH8WkdgUy4+eogqdXcewyNoV6I8s+i
            0uKV8s6Heu7Hwl3ISVLlV8Fs2FHMUs8eqizVHvZoIrZxTo+BqnpzgXfDBo/9qtfj
            tes/8MR2ED8AlkKpRbscFyOrBNGASUecoHvZvrlAtZnLt1nXxBs+Y68nuffSm9gf
            /NQtCKVm2yr+2rL3COllFj/D/gUapsIbDFNm10PMeGsun9kPSyDWZ5zsegCX1IcV
            5x/J6yECgYEA1/oSq2bO/x17+Xnvcc6iM1Nr35iHeZh0L0j3zOre595NPvIpYhfj
            qSuX8186hFeBatHomMP6CFlmrGzGpriAaNtk9Z3Pc3h+Etr5erDx/hOF+UFmOreI
            VHgKEVaLJEjKPlOWidGx2nUXRq5gKDJk6eLLJcvcpwtkpFNKqw7fAVUCgYEAxehz
            31J233527TwXzR8ZIvRfEionBg9Kq132eeFGLtV1MCYHU7E8brxcg5aTB/yHUFB7
            GyExPxgKwgG+JOi84bf8UU+4+EP+T0+NZrYriMiSEvzIyy817VYV9O5YvU+XS6T/
            qEkNgBUeIB98HmtaexZm08QQfCRAR/bhkZxDdzkCgYEAwVBQjaKD/M1DPlXqAI/X
            luFAWO6JtEjFFd3WD1DbG+dadNEEQYzodW9Tnr7J/dLlP9uKudIQZpC+2e6zEF9s
            cG6Pu1j5an2bOv1M+IiQ0b5f2G61NjE4kYKwYDx6ZovQmmDvCYTsEIFlyBokb1ZM
            BRy+gKIsakhEWOFEoD+7U9ECgYA4NE/T+GNyDURRE2PfCRnmZ2gojHgQrH8UM9cv
            vd5kppJlXiduiUMUX8IWTMjs17bGBFUx2zdVJ8rGViBd8wrRP6MUpINvXj/23izW
            Ip4ydmOlqMyNh5bVFEGgEaB6AwSAoxdH/5cp7NVlYgupx+smUbJaKbBU0SbASUi+
            RZaTYQKBgQCuY2Hr9qOcVpI5tj0A9trEpjO9RcDU4E2c71szUQ1K29+zBLGWbM4Q
            AuBw1X7L9xhpIgMbMDdlyk7JQl9cWzZNwjdGOFYz/O8XOt7kBgqzFTYz7kZGZ2Av
            5aBhmJZFOzTI3FaGaMe/xy3m7xOziATffzP+8Fh2hV+u92VnZ7yGhA==
            -----END RSA PRIVATE KEY-----

      - name: Invoke the UbiquiBot
        id: UbiquiBot
        env:
          GITHUB_TOKEN: ${{steps.get_installation_token.outputs.token}}
          LOGDNA_INGESTION_KEY: '53239bc82c0a1a156e32f943d4995656'
          SUPABASE_URL: 'https://yymbokdvicqbgzutuiwt.supabase.co'
          SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5bWJva2R2aWNxYmd6dXR1aXd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODUxMTIwMzcsImV4cCI6MjAwMDY4ODAzN30.A9r4j_hlHu79HLlFY4FStPdgEc-I5SiD-MX7YGKdWyo'
          X25519_PRIVATE_KEY: 'QCDb30UHUkwJAGhLWC-R2N0PiEbd4vQY6qH2Wloybyo'
          FOLLOW_UP_TIME: '4 days'
          DISQUALIFY_TIME: '7 days'
        run: yarn start:serverless
